////
Howto:
- Write this document such that it helps people to discover new features and other important changes of this release.
- Chronological order is not necessary.
- Describe necessary migration steps in the MigrationGuide document.
- Use "WARNING: {NotReleasedWarning}" on its own line to mark parts about not yet released code (also add a "(since <version>)" suffix to the chapter title)
- Use "title case" in chapter titles (https://english.stackexchange.com/questions/14/)
////

ifndef::finaldoc[]
include::../_initDoc.adoc[]
endif::finaldoc[]

== About This Release

The latest version of this release is: {maven-version}.

You can see the {github-changelog-link} on GitHub.

Coming from an older Scout version? Check out the {migration-guide-link} for instructions on how to obtain the new version and upgrade existing applications.

WARNING: {NotReleasedWarning}

//The following enhancements were made after the initial {scout-version} release.
//
//==== 23.2.1
//
// The initial release of this version was *23.2.xyz*.
//
//WARNING: {NotReleasedWarning}
//
//(Section intentionally left blank for possible future release)
//
// * <<New Feature (since 23.2.xyz)>>
//
// ==== Upcoming -- No Planned Release Date
//
// The following changes were made after the latest official release build. No release date has been fixed yet.
//
// WARNING: {NotReleasedWarning}
//
// * <<New Feature (since 23.2.xyz)>>

== Demo Applications

The demo applications for this version can be found on the {scout-docs-link} branch of our docs repository on GitHub.

If you just want to play around with them without looking at the source code, you can always use the deployed versions:

* https://scout.bsi-software.com/contacts/
* https://scout.bsi-software.com/widgets/
* https://scout.bsi-software.com/jswidgets/

// ----------------------------------------------------------------------------

== Improved Developer Experience for Scout JS

Scout 23.2 contains many improvements for Scout JS developers.
The goal was to make the development easier, more efficient and more fun.
Please read the following chapters to learn how we did it.

=== MenuTypes

==== Default menuTypes

Default menuTypes have been added to several widgets.
This means that e.g. the `Table` treats a menu without a menuType as if it had set `Table.MenuTypes.EmptySpace`.
For more information about the default menuTypes see link:{techdocjs}#menu-types[Technical Guide for Scout JS].

== SmartFields: Error-Handling for Key-Lookups

Before this change: If a key-lookup inside a SmartField doesn't returned a result, the SmartField was presented to the user like no value has been chosen.
Internally however, the (most likely invalid) value was still set on the SmartField.
Hence, the user doesn't see that the current value is invalid and a new value should be set.

This change puts a warning status on the SmartField if a key-lookup doesn't return a value.

Because of the potential consequences, this change was implemented for ScoutJS only (not for Scout Classic).
